apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-proj1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: sur1823/repo1:javaproj_1
        ports:
        - containerPort: 8786         #make sure to expose the container port:
